# Form implementation generated from reading ui file 'HighSetting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = StrongBodyLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 131, 41))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = ComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 50, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = ComboBox(parent=self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 120, 121, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_2 = StrongBodyLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 131, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = ComboBox(parent=self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(210, 250, 121, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_3 = StrongBodyLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 180, 131, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = StrongBodyLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 240, 131, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox_4 = ComboBox(parent=self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(210, 180, 121, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_5 = StrongBodyLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 50, 131, 41))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 120, 111, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = StrongBodyLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 50, 131, 41))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 120, 111, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "设置最大电压步进值"))
        self.comboBox.setPlaceholderText(_translate("MainWindow", "分辨率为1"))
        self.comboBox_2.setPlaceholderText(_translate("MainWindow", "分辨率为1"))
        self.label_2.setText(_translate("MainWindow", "设置最大电流步进值"))
        self.comboBox_3.setPlaceholderText(_translate("MainWindow", "分辨率为0.1"))
        self.label_3.setText(_translate("MainWindow", "设置最小电压步进值"))
        self.label_4.setText(_translate("MainWindow", "设置最小电流步进值"))
        self.comboBox_4.setPlaceholderText(_translate("MainWindow", "分辨率为0.1"))
        self.label_5.setText(_translate("MainWindow", "设备固件版本"))
        self.lineEdit.setText(_translate("MainWindow", "          V1.0.0"))
        self.label_6.setText(_translate("MainWindow", "上位机版本"))
        self.lineEdit_2.setText(_translate("MainWindow", "          V1.0.0"))
from qfluentwidgets import ComboBox, StrongBodyLabel
